### ISSUE TITLE
Location of current documentation

### ISSUE THREAD

**Issue by orodbhen** [vispy/vispy-website#3] opened 2016-03-12 12:47 UTC
The documentation seems to be located in about 3 different places. 

1 - Where you go when clicking on Documentation on the home page.
2 - At api.vispy.org.
3 - On readthedocs.

Which one is the most current?

**Comment by almarklein** [comment] 2016-03-12 19:19
api.vispy.org is just readthedocs, and read the docs is automatically updated on each commit in master, so that should be the latest. I am not sure why the website has its own docs rather than send the user to readthedocs.

**Comment by orodbhen** [comment] 2016-03-12 19:38
Great. Thanks. 

Also, there are no links to the actual documentation on the API home page. At least not that I can find. It can only be accessed via direct URL, e.g.

http://vispy.readthedocs.org/en/stable/scene.html

**Comment by orodbhen** [comment] 2016-03-12 19:54
Actually I can only access the stable version of the docs via readthedocs. The home page for "latest" has no documentation. There is a link to download the docs, though. 

The GitHub link is also broken, so I couldn't clone the docs and build them locally.

**Comment by djhoese** [comment] 2020-09-28 13:22
I'm going to mark this as a duplicate of https://github.com/vispy/vispy/issues/1374 just so we can keep things organized. I hope to have this all resolved in the coming month.

**Closed as completed by djhoese** 2020-09-28 13:22 UTC
